modLoader="javafml"
loaderVersion="[31,)"
[[mods]]
modId="netherleather"
version="1.0"
displayName="Nether Leather"
updateJSONURL="https://raw.githubusercontent.com/Redstoneguy129/Nether-Leather/master/Version.json"
authors="Redstoneguy129"
description='''
Adds leather drops to Zombie Pigmen
'''
[[dependencies.netherleather]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.netherleather]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
